# Name of the workflow
name: Code 

# When Workflow should run
on:
  push:

# Job in the workflows
jobs:
  code-checkout:
    runs-on: ubuntu-latest
     # Steps in the workflow
    steps:
      - name: Clone the code
        uses: actions/checkout@v7
         
      - name: Print the message
        run: echo "Code cloned"

  
